### PR TITLE
feat(wpa-pkgs): add rstudio.rstudio.2022.opensource

### LINKED ISSUE #209: [New Package]: RStudio.RStudio.OpenSource
### List the PackageIdentifier of the package to be added to automation

RStudio.RStudio.OpenSource

### Details about the application

We can get RStudio Desktop for Windows from this page. https://www.rstudio.com/products/rstudio/download/#download
Installer URL: https://download1.rstudio.org/desktop/windows/RStudio-2021.09.1-372.exe

The released version is linked to [the tag on the GitHub repository](https://github.com/rstudio/rstudio/tags) (e.g. `v2021.09.1+372`), but there may be a small time lag between when the tag is published and when the installer URL becomes active.

`+` in the version has been replaced by `-` in the installer URL.

### PR DESCRIPTION
**Pull request by eitsupi**
- [x] Have you verified that a previous version of the package is already there in the [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs)?
- [x] Have you validated the JSON with the [JSON Schema](https://raw.githubusercontent.com/vedantmgoyal2009/vedantmgoyal2009/main/winget-pkgs-automation/schema.json)?
- [x] Have you verified that the values entered in the JSON are correct?
- [x] The commit message(s) follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines.

Close #209

### CODE REVIEW

**Comment by eitsupi** [comment]
Could you please review this?
I have run the test script locally and it semms to be working well. Thanks!

**Comment by vedantmgoyal9** [comment]
Thanks for opening the pull request. I'll leave this for the next couple of days since we may need to change the package identifier on winget-pkgs repo. I'll change the package identifier and merge it then.

**Comment by vedantmgoyal9** [comment]
Sorry for so much delay. I'll try to review and merge faster next time.

**Comment by eitsupi** [comment]
Thank you for your review. Is there anything I can do?

**Comment by vedantmgoyal9** [comment]
No. I'm just testing my bot :) If it doesn't work, I'll merge manually. No worries 👍🏻

**Comment by eitsupi** [comment]
@vedantmgoyal2009 
Thank you for merging. But I do not understand your intention of changing the id.
Look at the main branch now, it looks like there are two files.

image

**Pull request merged**
