### PR TITLE
add steamdriddb.rommanager

### PR DESCRIPTION
**Pull request by Masamune3210**
Signed-off-by: Masamune3210 <1053504+Masamune3210@users.noreply.github.com>

### WinGet Automation Pull Request Checklist

- [ ] Have you verified that a previous version of the package is already there in the [Windows Package Manager Community Repository](https://github.com/microsoft/winget-pkgs)?
- [ ] Have you tested the package using the [`Test-Package`](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/tools/Test-Package.ps1) script, provided in the `tools` folder?
- [ ] The commit message(s) follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines.

### CODE REVIEW

**Comment by vedantmgoyal9** [comment]
@Masamune3210 adding package identifier in the list won't automatically update the package. You'll have to create a JSON for the package using New-Package script provided in tools folder.

**Comment by Masamune3210** [comment]
Ok, honestly forgot about this pull request, will probably just close it and work on it more when I have a chance

**Comment by Masamune3210** [comment]
Think I did it right, if not let me know and Ill try to fix it

**Comment by Masamune3210** [comment]
Test-Package wouldnt work, kept dying on line 174 and whining about a Missing file specification after redirection operator

**Review by vedantmgoyal9 — APPROVED** [review]

**Comment by vedantmgoyal9** [comment]
@allcontributors please add @Masamune3210 for code

**Pull request merged**
